CompileFlags:
  Add:
    - '-std=c++2a'
    - '-Wall'
    - '-Wextra'
    - '-Wshadow'
    - '-Wfloat-equal'
    - '-Wno-sign-conversion'
    - '-Wvla'
    - '-Wduplicated-cond'
    - '-Wlogical-op'
    - '-Wredundant-decls'
    - '-Winvalid-pch'
    - '-ggdb3'
    - '-D_GLIBCXX_DEBUG'
    - '-D_GLIBCXX_DEBUG_PEDANTIC'
    - '-D_FORTIFY_SOURCE=2'
    - '-fno-omit-frame-pointer'
    - '-fno-optimize-sibling-calls'
    - '-fstack-protector-all'
    - '-fno-sanitize-recover=all'
    - '-DDEBUG'
    - '-I/home/huyle/.template/'
